[project]
name = "gen-joint-mtide"
version = "0.2.0"
description = "Utilities to generate realistic movement time distributions for various user strategies"
readme = "README.md"
authors = [
    { name = "jgori", email = "juliengori@gmail.com" }
]
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "numpy>=2.1.1",
    "scipy>=1.14.1",
    "polars>=1.7.1",
    "matplotlib>=3.9.2",
    "seaborn>=0.13.2",
    "rpy2>=3.5.16",
    "statsmodels>=0.14.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
